import Head from "next/head";
import { HeroTitle } from "components/Hero";
import { Header } from "components/Header";
import { FooterSocial } from "components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Guest Book</title>
        <meta name="description" content="Generated by MicroDapps" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <HeroTitle />
        <FooterSocial />
      </main>
    </>
  );
}
