import { Container, Title, Accordion, createStyles, rem } from "@mantine/core";
import Head from "next/head";
import { Header } from "components/Header";
import { FooterSocial } from "components/Footer";
import { InstructionData } from "components/AccordianData";

const useStyles = createStyles((theme) => ({
  wrapper: {
    paddingTop: `calc(${theme.spacing.xl} * 2)`,
    paddingBottom: `calc(${theme.spacing.xl} * 2)`,
    minHeight: 650,
  },

  title: {
    marginBottom: `calc(${theme.spacing.xl} * 1.5)`,
  },

  item: {
    borderRadius: theme.radius.md,
    marginBottom: theme.spacing.lg,
    border: `${rem(1)} solid ${
      theme.colorScheme === "dark" ? theme.colors.dark[4] : theme.colors.gray[3]
    }`,
  },
}));

export default function Home() {
  const { classes } = useStyles();
  return (
    <>
      <Head>
        <title>Guest Book</title>
        <meta name="description" content="Generated by MicroDapps" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container size="sm" className={classes.wrapper}>
        <Title align="center" className={classes.title}>
          Contribution Instructions
        </Title>

        <InstructionData />
      </Container>
      <FooterSocial />
    </>
  );
}
